### ISSUE TITLE
getComments in map.js

### ISSUE THREAD

**Issue by ANDDYYYY** [food-mappers/food-mapper-app#55]
map.js got kind of fubarred.  there are two copies of the getComments function.

My idea for implementation worked a few commits ago..

It involved extracting the getComments call to only write into a comment container and having the show/hide dialog interaction kept out of that function.

Anyway, just saying I can repair it, but not tonight. assign me.

**Comment by mejackreed** [comment]
@ANDDYYYY What is fubared about it?

**Comment by mejackreed** [comment]
Fixed with 31723b9f6d741734f0a0e25fb8441d68fc8ef0ba
